# Site settings
title: My Insights
email: roberta@rvpolyak.com
description: > # this means to ignore newlines until "baseurl:"
  I have a passion for reading, running,finding out what makes companies great and other companies fail.
  My goal is to read 150 books in 2016, run a full marathon, and give my two thoughts on all the things I find fascinating along the way
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rvpolyak.com" # the base hostname & protocol for your site
twitter_username: seerobertarun

# Build settings
markdown: kramdown
