# Site settings
title: My Insights
email: roberta@rvpolyak.com
description: > # this means to ignore newlines until "baseurl:"
  I am interested in what makes some companies great and other companies fail.
  From time to time I like to sneak in my two thoughts on sports, nutrition and everything else in between.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rvpolyak.com" # the base hostname & protocol for your site
twitter_username: seerobertarun

# Build settings
markdown: kramdown
